version: '3'
services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    volumes:
      - ./data:/tmp
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db:27017/product
      SPRING_DATA_MONGODB_DATABASE: product

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
